- name: Ensure misc packages are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - etckeeper
  - sshguard
  - nano
  - vim
  - tcpdump
  - dnsutils
  - realpath
  - screen
  - tmux
  - htop
  - mlocate
  - git
  - tig
  - unattended-upgrades
