---
- name: Ensure gateways are up to date
  hosts: gateways
  roles:
    - apt_upgrade
  tags: apt_upgrade

- name: Ensure gateways are set up
  hosts: gateways
  roles:
    - noc_keys
    - gateway
    - mesh_vpn
    - mesh_vpn_ci_access
    - mesh_gre
    - bgp4 # Required for default route distribution
    - gateway_mss_clamp
  tags: gateway

- name: Ensure gateways are peered with ffnw via ipv6
  hosts: peering_ffnw6
  roles:
    - ffnw6
  tags: gateway

- name: Ensure gateways are peered with ffnw via ipv4
  hosts: peering_ffnw4
  roles:
    - ffnw4
  tags: gateway
