---
- name: Ensure packages are up to date
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_upgrade
  tags: apt_upgrade

- name: Reboot if kernel was updated
  reboot:
  when: '"linux-image" in apt_upgrade.stdout'
  tags: apt_upgrade
